# .go-arch-lint.yml
version: 3

allow:
  deepScan: false

excludeFiles:
  - "^.*_test\\.go$"
  - "mocks\\.*"
  - "proto\\.*"

vendors:
  go-std:              { in: "std" }
  go-log:              { in: "log/slog" }
  go-context:          { in: "context" }
  go-errors:           { in: "errors" }
  go-os:               { in: "os/signal" }
  go-time:             { in: "time" }

  3rd-grpc:            { in: "google.golang.org/grpc" }
  3rd-protoc-gen:      { in: "google.golang.org/protobuf" }
  3rd-solana-go:       { in: "github.com/gagliardetto/solana-go" }
  3rd-resty:           { in: "github.com/go-resty/resty/v2" }
  3rd-solana-rpc:      { in: "github.com/gagliardetto/solana-go/rpc" }
  3rd-solana-ws:       { in: "github.com/gagliardetto/solana-go/rpc/ws" }
  3rd-solana-send:     { in: "github.com/gagliardetto/solana-go/rpc/sendAndConfirmTransaction" }
  3rd-grpc-insecure:   { in: "google.golang.org/grpc/credentials/insecure" }
  3rd-grpc-reflection: { in: "google.golang.org/grpc/reflection" }
  3rd-grpc-status:     { in: "google.golang.org/grpc/status" }
  3rd-grpc-codes:      { in: "google.golang.org/grpc/codes" }

components:
  main:                { in: "cmd/app/**" }
  app:                 { in: "internal/app/**" }
  config:              { in: "internal/config/**" }
  logger:              { in: "internal/logger/**" }
  interface:           { in: "internal/interface/**" }
  entity:              { in: "internal/entity/**" }
  adapterGrpc:         { in: "internal/adapter/grpc/**" }
  adapterJupiter:      { in: "internal/adapter/jupiter/**" }
  adapterMexc:         { in: "internal/adapter/mexc/**" }
  apiJupiter:          { in: "internal/api/jupiter/**" }
  apiMexcSpot:         { in: "internal/api/mexc/spot/**" }
  apiMexcUtils:        { in: "internal/api/mexc/utils/**" }
  storage:             { in: "internal/storage/**" }
  service:             { in: "internal/service/**" }
  serviceScanner:      { in: "internal/service/scanner/**" }
  usecase:             { in: "internal/usecase/**" }
  controllerGrpc:      { in: "internal/controller/grpc/**" }
  controllerHttp:      { in: "internal/controller/http/**" }
  interceptors:        { in: "internal/controller/grpc/interceptors" }
  report:              { in: "internal/report/**" }
  solana:              { in: "internal/solana/**" }
  wallet:              { in: "internal/wallet/**" }
  proto:               { in: "proto/**" }
  client:              { in: "cmd/client/**" }

commonVendors:
  - go-std
  - go-log
  - go-context
  - go-errors
  - go-os
  - go-time

commonComponents:
  - interface
  - entity

deps:
  main:
    mayDependOn:
      - app
      - config
      - logger
    canUse:
      - go-errors
      - 3rd-grpc
      - 3rd-protoc-gen
      - 3rd-grpc-insecure
      - 3rd-grpc-reflection
      - 3rd-grpc-status
      - 3rd-grpc-codes

  app:
    mayDependOn:
      - config
      - logger
      - service
      - storage
      - adapterJupiter
      - adapterMexc
      - controllerGrpc
      - controllerHttp
      - serviceScanner
      - report
      - interface

  service:
    mayDependOn:
      - interface
      - entity
      - storage
      - logger
      - config
      - apiJupiter
      - report
      - apiMexcUtils
      - apiMexcSpot

  serviceScanner:
    mayDependOn:
      - interface
      - config

  usecase:
    mayDependOn:
      - interface
      - entity
      - logger
      - apiJupiter
      - solana
    canUse:
      - 3rd-solana-go

  controllerGrpc:
    mayDependOn:
      - proto
      - interceptors
    canUse:
      - 3rd-grpc
      - 3rd-grpc-reflection
      - 3rd-grpc-status
      - 3rd-grpc-codes

  interceptors:
    canUse:
      - 3rd-grpc

  apiMexcSpot:
    mayDependOn:
      - apiMexcUtils
    canUse:
      - 3rd-resty

  apiMexcUtils:
    canUse:
      - 3rd-resty

  adapterGrpc:
    mayDependOn:
      - proto

  adapterJupiter:
    mayDependOn:
      - apiJupiter

  adapterMexc:
    mayDependOn:
      - apiMexcSpot
      - apiMexcUtils

  storage:
    mayDependOn:
      - interface
      - entity
      - logger

  report:
    mayDependOn:
      - storage
      - logger
      - interface

  solana:
    mayDependOn:
      - interface
      - logger
    canUse:
      - 3rd-solana-go
      - 3rd-solana-rpc
      - 3rd-solana-send
      - 3rd-solana-ws

  wallet:
    mayDependOn:
      - interface
      - logger
      - solana
    canUse:
      - 3rd-solana-go

  config:
    mayDependOn: []
    anyVendorDeps: true

  logger:
    mayDependOn: []
    anyVendorDeps: true

  interface:
    canUse:
      - 3rd-solana-go

  entity:
    mayDependOn: []
    anyProjectDeps: true

  client:
    mayDependOn:
      - adapterGrpc
      - proto
    anyVendorDeps: true