log:
  level: 'debug'

exchanges:
  mexc:
    apiKey: ""
    secretKey: ""
    baseUrl: "https://api.mexc.com/api/v3"
    enabled: true
    orderLimit: 5
    maxPriceDiff: 0.01
    minQtyImprovement: 50

  jupiter:
    baseUrl: "https://lite-api.jup.ag/swap/v1"
    enabled: true

symbols:
  - SOLUSDT
  - BTCUSDT
  - ETHUSDT
  - DOGEUSDT
