log:
  level: 'info'

exchanges:
  mexc:
    apiKey: ""
    secretKey: ""
    baseUrl: "https://api.mexc.com/api/v3"
    enabled: true
    orderLimit: 5
    maxPriceDiff: 0.01
    minQtyImprovement: 50

  jupiter:
    baseUrl: "https://lite-api.jup.ag/swap/v1"
    baseUrlAdapter: "https://lite-api.jup.ag/swap/v1"
    timeout: 3s
    enabled: true
    pairs:
      SOL/USDT:
        base: "So11111111111111111111111111111111111111112"
        quote: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"

scanner:
  baseAmount: 0.7
  interval: "2s"
  pairs:
    - "SOL/USDT"
  logOpportunities: true
  buffers:
    prices: 0        # без буфера
    orderBooks: 1   # малый коалесцирующий буфер
    opportunities: 0 # события редки — можно 0

symbols:
  - SOLUSDT
  - BTCUSDT
  - ETHUSDT
  - DOGEUSDT
